# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  sync_youtube_channels:
    class: SyncYoutubeChannelsJob
    schedule: every hour at minute 0
    queue: ingestion

  sync_twitter_accounts:
    class: SyncTwitterAccountsJob
    schedule: every hour at minute 30
    queue: ingestion

  extract_all_pending_calls:
    class: ExtractAllPendingCallsJob
    schedule: every hour at minute 15
    queue: extraction

  fetch_all_prices:
    class: FetchAllPricesJob
    schedule: every day at 6am
    queue: prices

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

development:
  sync_youtube_channels:
    class: SyncYoutubeChannelsJob
    schedule: every 10 minutes

  sync_twitter_accounts:
    class: SyncTwitterAccountsJob
    schedule: every 10 minutes

  extract_all_pending_calls:
    class: ExtractAllPendingCallsJob
    schedule: every 10 minutes
